# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databrowser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='segmentation_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='segmentation_validationstatus',
            field=models.CharField(choices=[('1', 'Missing'), ('2', 'Invalidated'), ('3', 'Validated')], default='2', max_length=1),
        ),
    ]
